### ISSUE TITLE
Tool detail page

### ISSUE THREAD

**Issue by andrea-halloran** [samurai-i-am-awry/retool#16]
![image 4](https://user-images.githubusercontent.com/37048730/50377270-aecc9600-05df-11e9-9a64-74b551960374.png)

**Comment by theperfectpunk** [comment]
I'll be working on this one

**Comment by mihirkothari25** [comment]
I'm sorry, but this is a project for a class that we will be graded on, so we cannot allow outsiders to work on it.

**Comment by andrea-halloran** [comment]
This has been completed.
